### ISSUE TITLE
train ReID logs

### ISSUE THREAD

**Issue by EnzoLiang** [NirAharon/BoT-SORT#14]
Hi @NirAharon ，
I am training ReID model on MOT20, but the training results is abnormal. As shown in the figure below，loss_cls is instability and lr  remains the same after 2000 iters. Do you have the same problem when you train this model.
![reid](https://user-images.githubusercontent.com/27463147/180174813-6fc76093-c834-437b-bde3-a326e183b439.png)

**Comment by NirAharon** [comment]
Hi @EnzoLiang,
It is likely because of the CosineAnnealingLR scheduler.  
I don't recall any problem when I trained this network, but it was a long time ago. I will try to find the training log. 
If you still have trouble, maybe you be able to find more information at the FastReID repo or try and change the LR scheduler.

**Comment by EnzoLiang** [comment]
Hi @NirAharon, 
The results are  unchanged when I change the LR scheduler to MultiStepLR.  It is normal to train on Market1501 datasets using the same yaml config. Is it related to the generated MOT20 dataset?


> Hi @EnzoLiang, It is likely because of the CosineAnnealingLR scheduler. I don't recall any problem when I trained this network, but it was a long time ago. I will try to find the training log. If you still have trouble, maybe you be able to find more information at the FastReID repo or try and change the LR scheduler.

**Comment by HanGuangXin** [comment]
@EnzoLiang Hi, have you solved the issue? What is the reason of that?
