### ISSUE TITLE
REID

### ISSUE THREAD

**Issue by huanglong161** [NirAharon/BoT-SORT#28]
Why do I report this error when training the pedestrian re recognition model? The mot17 data set generated according to your document.
File "rank_cy.pyx", line 20, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 28, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 240, in rank_cy.eval_market1501_cy
AssertionError: Error: all query identities do not appear in gallery

**Comment by NirAharon** [comment]
It is because I didn't create any query folder for ranking evaluation. 
MOT17 and MOT20 aren't officially ReID datasets like Market1501.
If you need this type of evaluation, you can change the generate_mot_patches.py to output query and gt_query as in Market1501. 

Also, pay attention to that you will need to compile with Cython to accelerate evolution, as follow:
cd fastreid/evaluation/rank_cylib; make all

Good luck!

**Comment by gubei528** [comment]
> Why do I report this error when training the pedestrian re recognition model? The mot17 data set generated according to your document. File "rank_cy.pyx", line 20, in rank_cy.evaluate_cy File "rank_cy.pyx", line 28, in rank_cy.evaluate_cy File "rank_cy.pyx", line 240, in rank_cy.eval_market1501_cy AssertionError: Error: all query identities do not appear in gallery

Is this problem solved?

**Comment by gubei528** [comment]
how can i generate query and gt_query as in Market1501

**Comment by farahmand-m** [comment]
Can you explain the additional directories a bit further? What are they supposed to contain?

**Comment by farahmand-m** [comment]
For anyone who needs further info on what these directories need to include, read [here](https://zheng-lab.cecs.anu.edu.au/Project/project_reid.html#:~:text=The%20package%20contains%20four%20folders.).

**Comment by AleksanderB31** [comment]
Has anyone succeeded doing this?

**Comment by BrendanWooAdmetal** [comment]
## Duplicate issues
This issue is a duplicate of several others;
[Issue 117](https://github.com/NirAharon/BoT-SORT/issues/117#issue-2559658071)
[Issue 83](https://github.com/NirAharon/BoT-SORT/issues/83)
[Issue 51](https://github.com/NirAharon/BoT-SORT/issues/51)

## Issue cause
The training code comes from [FastReID](https://github.com/JDAI-CV/fast-reid/tree/master).

The code was designed to run on the Market1501 dataset, and is used for validation.
It assumes the dataset given has several directories.
See the [README for Market1501](https://www.kaggle.com/datasets/pengcw1/market-1501/data) to see a full explanation.

However, MOT17 does not have all of these directories, so when the model tries to run an evaluation, it throws an error.
This evaluation is simply a check of how well the training is doing using the data in the other directories that we are lacking.

It seems the original devs got around this by simply disabling the check, allowing you to run training without doing the evaluation.
See the [post above](https://github.com/NirAharon/BoT-SORT/issues/28#issuecomment-1214975808).

Disabling the check was accomplished by modifying the [config for Base-SBS.yml](https://github.com/NirAharon/BoT-SORT/blob/main/fast_reid/configs/Base-SBS.yml).
The EVAL_PERIOD was set very high, so the evaluation never triggers.
It is set to 1000; in the original FastReID code, it is only 10.
Since we train for only 60 epochs with Base-SBS.yaml, it never does the evaluation and never crashes.

The issue is that while Base-SBS.yaml has been modified to disable this check, the other configs haven't.

For example, I tried to train a R50-ibn model from FastReID using the techniques in BoT-SORT's docs, but got the same error at epoch 30 when it tries to run evaluation.
`AssertionError: Error: all query identities do not appear in gallery`

## Workaround
The solution was to modify the configuration file I was using to set EVAL_PERIOD to a very large number so it never tries to run evaluation code that doesn't work on MOT17 or MOT20's dataset format.
In my case, this was [Base-bagtricks.yml](https://github.com/NirAharon/BoT-SORT/blob/main/fast_reid/configs/Base-bagtricks.yml).
Be sure to modify the configuration for the model that you are using.
It may still throw the error when it tries to evaluate at the end, but everything is done by that point.

This is just a workaround that sidesteps the issue and allows you to train other models besides the S50-sbs one using MOT17 or MOT20.
As noted by the devs, if you want this type of validation, you will need to modify generate_mot_patches.py to output data in the relevant format.
