### ISSUE TITLE
what args do I need to pass for BoTSORT

### ISSUE THREAD

**Issue by Sumant-Gosi** [NirAharon/BoT-SORT#66]
I am integrating Yolov8, botSORT in my application. 

And ofcourse, I am getting the issue of missing 1 argument 'args' for BOTSORT().
So, what args do I pass in order to produce the tracking results ?
I did set args='without_reid' , I get  missing argument for 'track_buffer'.

So, where do I find the argument list for BoTSORT ?

**Comment by Sumant-Gosi** [comment]
Got it.

Sorry for the inconvenience

**Comment by migsdigs** [comment]
@Sumant-Gosi Hi, could I possibly see your integration of Yolov8 please?

**Comment by RaffelRavionaldo** [comment]
@Sumant-Gosi @migsdigs Hello, May I know how you use this repo with yolov8?

**Comment by migsdigs** [comment]
> [@Sumant-Gosi](https://github.com/Sumant-Gosi) [@migsdigs](https://github.com/migsdigs) Hello, May I know how you use this repo with yolov8?

Hi @RaffelRavionaldo, you can integrate yolov8 by altering some of the code from the `mc_demo_yolov7.py` file. Because yolov8 is a lot more self-contained you don't need many of the parameters that are needed for the yolov7 example. I will put some snippets below that should hopefully help you:

Initialize model:
```
 Initialize YOLOv8 model
    if opt.weights == 'pretrained/rtdetr-l.pt' or opt.weights == 'pretrained/rtdetr-x.pt':
        model = RTDETR(opt.weights)
    else:
        model = YOLO(opt.weights)
```

Then inside of the `detect(opt)` function you will run the detector inference to the detections:
```
# Run YOLOv8 inference (place detection model here)
        results = model(frame,
                        conf=opt.conf_thres,
                        iou=opt.iou_thres,
                        max_det=opt.max_det,
                        classes=opt.classes if hasattr(opt, 'classes') else None,
                        agnostic_nms=opt.agnostic_nms,
                        augment=opt.augment,
                        half=opt.half,
                        verbose=False)[0]
```

Then, I think most importantly, you change the format of your detection data to pass it to the `update()` function of the tracker:
```
# Convert YOLOv8 detections to format expected by BoT-SORT
        # Format: [x1, y1, x2, y2, confidence, class]
        detections = []
        if len(results.boxes) > 0:
            for box in results.boxes:
                x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
                conf = box.conf[0].cpu().numpy()
                cls = box.cls[0].cpu().numpy()
                detections.append([x1, y1, x2, y2, conf, cls])

        detections = np.array(detections) if len(detections) > 0 else np.empty((0, 6))

        # Update tracker with new detections
        online_targets = tracker.update(detections, frame)
```

I hope this helps!

What I have found is that BoTSORT is very good with reid enabled, but then it is very slow and doesn't seem suitable for real time. If you are looking to run a simple, fast tracker, I would consider ByteTrack.

**Comment by RaffelRavionaldo** [comment]
Hello @migsdigs , Thank you for your help and advice. I will try it.
